version: '3.8'
services:
  react-app:
    container_name: docker-standalone-html-c
    image: docker-standalone-html-i
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '3000:3000'
    volumes:
      - './:/app'
