name: Build and push harbor

concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true

on:
  workflow_dispatch:
    inputs:
      target_deployment:
        description: 'Target Deployment'
        required: true
        default: 'dev'
        type: choice
        options:
          - "dev"
          - "staging"
          - "prod"
  push:
    # branches:
    #   - main
    tags:
      - 'v.[0-9]+.[0-9]+.[0-9]+'      

jobs:
  build:
    runs-on: [ubuntu-latest]
    # runs-on: [self-hosted, macOS, ARM64]
    steps:
    - uses: actions/checkout@v3
      with:
        persist-credentials: false
    - name: Run build and push docker to harbor
      run: sh ./scripts/build_harbor.sh
      env:
        VERSION: ${{ github.event.inputs.target_deployment }}
        COMMIT_SHA: ${{ github.sha }}
        HARBOR_USER: ${{ secrets.HARBOR_USER }}
        HARBOR_PASS: ${{ secrets.HARBOR_PASS }}
